import Head from 'next/head'
import { Inter } from 'next/font/google'
import Router from 'next/router'



const inter = Inter({ subsets: ['latin'] })
Router.push('/en')
export default function Home() {
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
    </>
  )
}


export async function getStaticPaths() {
  const paths = [
    { params: { uri: ['home'] } },
    { params: { uri: ['about'] } },
    { params: { uri: ['contact'] } },
  ];

  return {
    paths,
    fallback: false,
  };
}
